### ISSUE TITLE
Suggest 3 good papers (Deadline 3/8)

### ISSUE THREAD

**Issue by GindaChen** [open-lambda/s19-apps#2]

**Comment by GindaChen** [comment]
**Sapphire**:
http://sapphire.cs.washington.edu/papers/sapphire-osdi14.pdf

**Comment by aditya2397** [comment]
**LAVEA**:
http://www.cs.wayne.edu/~weisong/papers/yi17-LAVEA.pdf

**Comment by GindaChen** [comment]
@dereklh4  @joelhaynie Just a reminder that we shall contribute 3 papers by Friday 😄

**Comment by dereklh4** [comment]
CloudPath: A Multi-Tier Cloud Computing Framework: http://sysweb.cs.toronto.edu/publication_files/0000/0309/sedgec17-final51.pdf

**Comment by GindaChen** [comment]
LAVEA:
http://www.cs.wayne.edu/~weisong/papers/yi17-LAVEA.pdf
CloudPath: A Multi-Tier Cloud Computing Framework: http://sysweb.cs.toronto.edu/publication_files/0000/0309/sedgec17-final51.pdf
Sapphire:
http://sapphire.cs.washington.edu/papers/sapphire-osdi14.pdf
